global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'paksa-backend'
    static_configs:
      - targets: ['paksa-backend-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'paksa-frontend'
    static_configs:
      - targets: ['paksa-frontend-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s