apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: paksa-backend-hpa
  namespace: paksa-financial
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paksa-backend
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: paksa-frontend-hpa
  namespace: paksa-financial
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paksa-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60