"""Initial migration

Revision ID: 9afb31e0b162
Revises: 
Create Date: 2025-07-27 22:21:37.537466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9afb31e0b162'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('budget_name', sa.String(length=200), nullable=False),
    sa.Column('budget_year', sa.Integer(), nullable=False),
    sa.Column('budget_period', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_index(op.f('ix_budgets_tenant_id'), 'budgets', ['tenant_id'], unique=False)
    op.create_table('cash_accounts',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_accounts_id'), 'cash_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_cash_accounts_tenant_id'), 'cash_accounts', ['tenant_id'], unique=False)
    op.create_table('companies',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('default_language', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year_start', sa.String(length=5), nullable=False),
    sa.Column('tax_settings', sa.JSON(), nullable=True),
    sa.Column('enabled_modules', sa.JSON(), nullable=True),
    sa.Column('numbering_formats', sa.JSON(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('database_schema', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('company_settings',
    sa.Column('company_id', sa.String(36), nullable=False),
    sa.Column('chart_of_accounts_template', sa.String(length=50), nullable=True),
    sa.Column('approval_workflows', sa.JSON(), nullable=True),
    sa.Column('integrations', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('security_settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_settings_company_id'), 'company_settings', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_settings_id'), 'company_settings', ['id'], unique=False)
    op.create_table('company_users',
    sa.Column('company_id', sa.String(36), nullable=False),
    sa.Column('user_id', sa.String(36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_users_company_id'), 'company_users', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_users_id'), 'company_users', ['id'], unique=False)
    op.create_index(op.f('ix_company_users_user_id'), 'company_users', ['user_id'], unique=False)
    op.create_table('customers',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('customer_code', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('gl_accounts',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('parent_account_id', sa.String(36), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.ForeignKeyConstraint(['parent_account_id'], ['gl_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_accounts_account_code'), 'gl_accounts', ['account_code'], unique=False)
    op.create_index(op.f('ix_gl_accounts_id'), 'gl_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_gl_accounts_tenant_id'), 'gl_accounts', ['tenant_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('entry_number', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_number')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_tenant_id'), 'journal_entries', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('tenant_id', sa.String(36), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vendors',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('vendor_code', sa.String(length=20), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_code')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.create_table('ap_invoices',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('vendor_id', sa.String(36), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.String(length=10), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_invoices_id'), 'ap_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_ap_invoices_tenant_id'), 'ap_invoices', ['tenant_id'], unique=False)
    op.create_table('ap_payments',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('vendor_id', sa.String(36), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_payments_id'), 'ap_payments', ['id'], unique=False)
    op.create_index(op.f('ix_ap_payments_tenant_id'), 'ap_payments', ['tenant_id'], unique=False)
    op.create_table('ar_invoices',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('customer_id', sa.String(36), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.String(length=10), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ar_invoices_id'), 'ar_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_ar_invoices_tenant_id'), 'ar_invoices', ['tenant_id'], unique=False)
    op.create_table('ar_payments',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('customer_id', sa.String(36), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ar_payments_id'), 'ar_payments', ['id'], unique=False)
    op.create_index(op.f('ix_ar_payments_tenant_id'), 'ar_payments', ['tenant_id'], unique=False)
    op.create_table('budget_line_items',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('budget_id', sa.String(36), nullable=False),
    sa.Column('account_id', sa.String(36), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('budgeted_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_line_items_id'), 'budget_line_items', ['id'], unique=False)
    op.create_index(op.f('ix_budget_line_items_tenant_id'), 'budget_line_items', ['tenant_id'], unique=False)
    op.create_table('cash_transactions',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('cash_account_id', sa.String(36), nullable=False),
    sa.Column('transaction_date', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cash_account_id'], ['cash_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_transactions_id'), 'cash_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_cash_transactions_tenant_id'), 'cash_transactions', ['tenant_id'], unique=False)
    op.create_table('journal_entry_lines',
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('journal_entry_id', sa.String(36), nullable=False),
    sa.Column('account_id', sa.String(36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('updated_by', sa.String(36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_lines_id'), 'journal_entry_lines', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entry_lines_tenant_id'), 'journal_entry_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entry_lines_tenant_id'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_id'), table_name='journal_entry_lines')
    op.drop_table('journal_entry_lines')
    op.drop_index(op.f('ix_cash_transactions_tenant_id'), table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_id'), table_name='cash_transactions')
    op.drop_table('cash_transactions')
    op.drop_index(op.f('ix_budget_line_items_tenant_id'), table_name='budget_line_items')
    op.drop_index(op.f('ix_budget_line_items_id'), table_name='budget_line_items')
    op.drop_table('budget_line_items')
    op.drop_index(op.f('ix_ar_payments_tenant_id'), table_name='ar_payments')
    op.drop_index(op.f('ix_ar_payments_id'), table_name='ar_payments')
    op.drop_table('ar_payments')
    op.drop_index(op.f('ix_ar_invoices_tenant_id'), table_name='ar_invoices')
    op.drop_index(op.f('ix_ar_invoices_id'), table_name='ar_invoices')
    op.drop_table('ar_invoices')
    op.drop_index(op.f('ix_ap_payments_tenant_id'), table_name='ap_payments')
    op.drop_index(op.f('ix_ap_payments_id'), table_name='ap_payments')
    op.drop_table('ap_payments')
    op.drop_index(op.f('ix_ap_invoices_tenant_id'), table_name='ap_invoices')
    op.drop_index(op.f('ix_ap_invoices_id'), table_name='ap_invoices')
    op.drop_table('ap_invoices')
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_journal_entries_tenant_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_gl_accounts_tenant_id'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_accounts_id'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_accounts_account_code'), table_name='gl_accounts')
    op.drop_table('gl_accounts')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_company_users_user_id'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_id'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_company_id'), table_name='company_users')
    op.drop_table('company_users')
    op.drop_index(op.f('ix_company_settings_id'), table_name='company_settings')
    op.drop_index(op.f('ix_company_settings_company_id'), table_name='company_settings')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_cash_accounts_tenant_id'), table_name='cash_accounts')
    op.drop_index(op.f('ix_cash_accounts_id'), table_name='cash_accounts')
    op.drop_table('cash_accounts')
    op.drop_index(op.f('ix_budgets_tenant_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###