<template>
  <div class="hrm-reports">
    <div class="flex justify-content-between align-items-center mb-4">
      <div>
        <h1>HR Reports</h1>
        <p class="text-color-secondary">Generate and view HR analytics and reports</p>
      </div>
    </div>

    <div class="grid">
      <div class="col-12 md:col-6 lg:col-4" v-for="report in reports" :key="report.id">
        <Card class="cursor-pointer hover:shadow-3 transition-all transition-duration-200" @click="generateReport(report)">
          <template #content>
            <div class="flex align-items-center">
              <div class="flex align-items-center justify-content-center w-3rem h-3rem border-circle mr-3" :class="report.iconClass">
                <i :class="report.icon" class="text-xl"></i>
              </div>
              <div>
                <div class="font-medium text-lg">{{ report.title }}</div>
                <div class="text-color-secondary text-sm">{{ report.description }}</div>
              </div>
            </div>
          </template>
        </Card>
      </div>
    </div>

    <Card class="mt-4">
      <template #title>Recent Reports</template>
      <template #content>
        <DataTable :value="recentReports" :loading="loading">
          <Column field="name" header="Report Name" sortable />
          <Column field="type" header="Type" sortable />
          <Column field="generatedBy" header="Generated By" sortable />
          <Column field="generatedAt" header="Generated At" sortable />
          <Column field="status" header="Status" sortable>
            <template #body="{ data }">
              <Tag :value="data.status" :severity="getStatusSeverity(data.status)" />
            </template>
          </Column>
          <Column header="Actions">
            <template #body="{ data }">
              <Button icon="pi pi-download" class="p-button-text p-button-success" @click="downloadReport(data)" />
              <Button icon="pi pi-eye" class="p-button-text" @click="viewReport(data)" />
            </template>
          </Column>
        </DataTable>
      </template>
    </Card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useToast } from 'primevue/usetoast';

interface Report {
  id: number;
  title: string;
  description: string;
  icon: string;
  iconClass: string;
  type: string;
}

interface RecentReport {
  id: number;
  name: string;
  type: string;
  generatedBy: string;
  generatedAt: string;
  status: string;
}

const toast = useToast();
const loading = ref(false);

const reports = ref<Report[]>([
  { id: 1, title: 'Employee Directory', description: 'Complete employee listing', icon: 'pi pi-users', iconClass: 'bg-blue-100 text-blue-600', type: 'directory' },
  { id: 2, title: 'Attendance Report', description: 'Employee attendance summary', icon: 'pi pi-clock', iconClass: 'bg-green-100 text-green-600', type: 'attendance' },
  { id: 3, title: 'Leave Report', description: 'Leave usage and balances', icon: 'pi pi-calendar', iconClass: 'bg-orange-100 text-orange-600', type: 'leave' },
  { id: 4, title: 'Payroll Summary', description: 'Payroll costs and breakdown', icon: 'pi pi-dollar', iconClass: 'bg-purple-100 text-purple-600', type: 'payroll' },
  { id: 5, title: 'Training Report', description: 'Training completion status', icon: 'pi pi-book', iconClass: 'bg-indigo-100 text-indigo-600', type: 'training' },
  { id: 6, title: 'Turnover Analysis', description: 'Employee turnover metrics', icon: 'pi pi-chart-line', iconClass: 'bg-red-100 text-red-600', type: 'turnover' }
]);

const recentReports = ref<RecentReport[]>([]);

const generateReport = (report: Report) => {
  toast.add({
    severity: 'info',
    summary: 'Report Generation',
    detail: `Generating ${report.title}...`,
    life: 3000
  });
};

const downloadReport = (report: RecentReport) => {
  toast.add({
    severity: 'success',
    summary: 'Download Started',
    detail: `Downloading ${report.name}`,
    life: 3000
  });
};

const viewReport = (report: RecentReport) => {
  toast.add({
    severity: 'info',
    summary: 'View Report',
    detail: `Opening ${report.name}`,
    life: 3000
  });
};

const getStatusSeverity = (status: string) => {
  switch (status.toLowerCase()) {
    case 'completed': return 'success';
    case 'processing': return 'warning';
    case 'failed': return 'danger';
    default: return 'info';
  }
};

onMounted(async () => {
  loading.value = true;
  try {
    await new Promise(resolve => setTimeout(resolve, 1000));
    recentReports.value = [
      { id: 1, name: 'Monthly Attendance Report', type: 'Attendance', generatedBy: 'John Doe', generatedAt: '2024-01-15 10:30 AM', status: 'Completed' },
      { id: 2, name: 'Employee Directory', type: 'Directory', generatedBy: 'Jane Smith', generatedAt: '2024-01-14 02:15 PM', status: 'Completed' },
      { id: 3, name: 'Payroll Summary Q4', type: 'Payroll', generatedBy: 'Mike Johnson', generatedAt: '2024-01-13 09:45 AM', status: 'Processing' }
    ];
  } finally {
    loading.value = false;
  }
});
</script>

<style scoped>
.hrm-reports {
  padding: 0;
}
</style>